import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export const dynamic = 'force-dynamic';

type RouteContext = { params: Promise<{ id: string }> };

// GET /api/business/[id]/export — Export business plan as Markdown
export async function GET(
  _request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;

    const business = await db.business.findUnique({
      where: { id },
      include: {
        planSteps: { orderBy: { stepNumber: 'asc' } },
        milestones: { orderBy: { targetDate: 'asc' } },
        financials: { orderBy: { createdAt: 'asc' } },
        tasks: { orderBy: [{ priority: 'desc' }, { createdAt: 'desc' }] },
      },
    });

    if (!business) {
      return NextResponse.json(
        { success: false, error: 'Business not found' },
        { status: 404 }
      );
    }

    const completedSteps = business.planSteps.filter((s) => s.status === 'completed');
    const progress = business.planSteps.length > 0
      ? Math.round((completedSteps.length / business.planSteps.length) * 100)
      : 0;

    const dateStr = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let markdown = `# ${business.name}\n\n`;
    markdown += `## Business Plan\n\n`;
    markdown += `> Generated by Tashyeed on ${dateStr}\n\n`;
    markdown += `---\n\n`;

    // Executive Summary
    markdown += `## Executive Summary\n\n`;
    markdown += `**Business Name:** ${business.name}\n\n`;
    markdown += `**Industry:** ${business.industry || 'Not specified'}\n\n`;
    markdown += `**Stage:** ${business.stage}\n\n`;
    markdown += `**Target Market:** ${business.targetMarket || 'Not specified'}\n\n`;
    markdown += `**Revenue Model:** ${business.revenueModel || 'Not specified'}\n\n`;
    markdown += `**Initial Capital:** $${business.initialCapital.toLocaleString()}\n\n`;
    markdown += `**Monthly Burn Rate:** $${business.monthlyBurnRate.toLocaleString()}\n\n`;
    markdown += `**Plan Progress:** ${completedSteps.length}/${business.planSteps.length} steps completed (${progress}%)\n\n`;
    markdown += `**Description:**\n\n${business.description}\n\n`;
    markdown += `---\n\n`;

    // Plan Steps
    markdown += `## Strategic Plan — Step by Step\n\n`;
    for (const step of business.planSteps) {
      const statusIcon = step.status === 'completed' ? '[x]' : (step.status === 'in_progress' || step.status === 'current') ? '[~]' : '[ ]';
      markdown += `### Step ${step.stepNumber}: ${step.title} ${statusIcon}\n\n`;
      markdown += `**Category:** ${step.category}\n\n`;
      markdown += `**Status:** ${step.status.replace(/_/g, ' ')}\n\n`;
      markdown += `**Estimated Duration:** ${step.estimatedDays} days\n\n`;
      if (step.description) markdown += `**Description:** ${step.description}\n\n`;
      if (step.guidance) markdown += `**Guidance:** ${step.guidance}\n\n`;
      if (step.tips) markdown += `**Expert Tips:** ${step.tips}\n\n`;

      // Checklist
      try {
        const checklist = JSON.parse(step.checklist || '[]') as string[];
        if (checklist.length > 0) {
          markdown += `**Checklist:**\n\n`;
          for (const item of checklist) {
            const done = item.startsWith('✅');
            markdown += `- ${done ? '[x]' : '[ ]'} ${item.replace(/^[✅⬜]\s*/, '')}\n`;
          }
          markdown += `\n`;
        }
      } catch { /* ignore */ }

      // Resources
      try {
        const resources = JSON.parse(step.resources || '[]') as string[];
        if (resources.length > 0) {
          markdown += `**Resources:**\n\n`;
          for (const r of resources) markdown += `- ${r}\n`;
          markdown += `\n`;
        }
      } catch { /* ignore */ }

      if (step.completedAt) {
        markdown += `*Completed on: ${new Date(step.completedAt).toLocaleDateString()}*\n\n`;
      }

      markdown += `---\n\n`;
    }

    // Milestones
    if (business.milestones.length > 0) {
      markdown += `## Milestones\n\n`;
      markdown += `| Milestone | Category | Target Date | Status | Progress |\n`;
      markdown += `|-----------|----------|-------------|--------|----------|\n`;
      for (const m of business.milestones) {
        const progress = m.targetValue > 0
          ? `${Math.round((m.currentValue / m.targetValue) * 100)}%`
          : '—';
        markdown += `| ${m.title} | ${m.category} | ${m.targetDate ? new Date(m.targetDate).toLocaleDateString() : '—'} | ${m.status.replace(/_/g, ' ')} | ${progress} |\n`;
      }
      markdown += `\n---\n\n`;
    }

    // Financial Summary
    if (business.financials.length > 0) {
      const totalRevenue = business.financials.filter(f => !f.projection).reduce((s, f) => s + f.revenue, 0);
      const totalExpenses = business.financials.filter(f => !f.projection).reduce((s, f) => s + f.expenses, 0);
      const latestActual = business.financials.filter(f => !f.projection).pop();
      const runway = latestActual?.runway ?? 0;

      markdown += `## Financial Summary\n\n`;
      markdown += `**Total Revenue (Actual):** $${totalRevenue.toLocaleString()}\n\n`;
      markdown += `**Total Expenses (Actual):** $${totalExpenses.toLocaleString()}\n\n`;
      markdown += `**Net Profit/Loss:** $${(totalRevenue - totalExpenses).toLocaleString()}\n\n`;
      markdown += `**Runway:** ${runway > 50 ? '50+' : runway} months\n\n`;

      markdown += `### Financial Breakdown\n\n`;
      markdown += `| Period | Revenue | Expenses | Profit | Customers | Type |\n`;
      markdown += `|--------|---------|----------|--------|-----------|------|\n`;
      for (const f of business.financials) {
        markdown += `| ${f.period} | $${f.revenue.toLocaleString()} | $${f.expenses.toLocaleString()} | $${f.profit.toLocaleString()} | ${f.customers} | ${f.projection ? 'Projection' : 'Actual'} |\n`;
      }
      markdown += `\n---\n\n`;
    }

    // Active Tasks
    const activeTasks = business.tasks.filter(t => t.status !== 'completed' && t.status !== 'cancelled');
    if (activeTasks.length > 0) {
      markdown += `## Action Items\n\n`;
      for (const t of activeTasks) {
        const priority = t.priority.toUpperCase();
        markdown += `- **[${priority}]** ${t.title}`;
        if (t.dueDate) markdown += ` *(Due: ${new Date(t.dueDate).toLocaleDateString()})*`;
        markdown += `\n`;
        if (t.description) markdown += `  ${t.description}\n`;
      }
      markdown += `\n---\n\n`;
    }

    markdown += `---\n\n*This business plan was generated by Tashyeed — Your AI-Powered Business Planning Partner.*\n`;

    return new NextResponse(markdown, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${business.name.replace(/[^a-z0-9]/gi, '_')}_business_plan.md"`,
      },
    });
  } catch (error) {
    console.error('[GET /api/business/[id]/export]', error);
    return NextResponse.json(
      { success: false, error: 'Failed to export business plan' },
      { status: 500 }
    );
  }
}
